// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (data.badge) {
    renderLicenseLink();
    return `![license](${badgeUrl})`
  }
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if (data.badge) {
    const badgeURL = `https://img.shields.io/badge/license-${data.badge}-informational`
    return badgeUrl
  }
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (data.badge) {
    const badgeFinalAssembly = renderLicenseBadge()
    const badgeComplete = `### License
                          ${badgeFinalAssembly}\n\n`
    return badgeComplete
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  renderLicenseSection();
  return `
# ${data.projectname}\n
${badgeComplete}
### Description\n
${data.description}\n\n
### Index\n
- [Installation](#installation)
- [Usage Information](#usage)
- [Contribute](#contribute)
- [Testing](#testing)
- [Questions](#questions)\n
### Installation\n
${data.installation}\n\n
### Usage\n
${data.usage}\n\n
### Contribute\n
${data.contribute}\n\n
### Testing
${data.test}
### Questions?
For questions or comments feel free to reach out:\n
* **Email**:  [${data.email}](mailto:${data.email})
* **GitHub Profile**:  [${data.username}](https://github.com/${data.username})\n\n\n
----
<sub>Generated by Professional README Generator | 0.2.0 | 2021</sub>
`;
}

module.exports = generateMarkdown;
