function renderLicenseBadge(data) {
  const getBadgeLink = renderLicenseLink(data);
  return `![license](${getBadgeLink})`
}

function renderLicenseLink(data) {
  const badgeUrl = `https://img.shields.io/badge/license-${data.badge}-informational`
  return badgeUrl;
}

function renderLicenseSection(data) {
  if (data.badge) {
    renderLicenseBadge(data)
    return `### License
    ${badgeConstruct}\n\n`
  }
}

function generateMarkdown(data) {
  const badgeConstruct = renderLicenseBadge(data)
  return `
# ${data.projectname}\n
### Description\n
${data.description}\n\n
### License
${badgeConstruct}\n\n
### Index\n
- [Installation](#installation)
- [Usage Information](#usage)
- [Contribute](#contribute)
- [Testing](#testing)
- [Questions](#questions)\n
### Installation\n
${data.installation}\n\n
### Usage\n
${data.usage}\n\n
### Contribute\n
${data.contribute}\n\n
### Testing
${data.test}
### Questions?
For questions or comments feel free to reach out:\n
* **Email**:  [${data.email}](mailto:${data.email})
* **GitHub Profile**:  [${data.username}](https://github.com/${data.username})\n\n\n
----
<sub>Generated by Professional README Generator | 0.2.5 | 2021</sub>
`;
}

module.exports = generateMarkdown;
