// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(datas) {
  /*
  if (datas.data.badge) {
    renderLicenseLink();
    const badgeConstruct = `![license](${badgeUrl})`
    console.log(`renderLicenseBadge:  ${badgeConstruct}`);
  }
  */
  renderLicenseLink()
  const badgeConstruct = `![license](${badgeUrl})`
  console.log(`renderLicenseBadge:  ${badgeConstruct}`);
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(data) {
  /*
  if (data.badge) {
    const badgeUrl = `https://img.shields.io/badge/license-${data.badge}-informational`
    console.log(`renderLicenseLink:  ${badgeUrl}`);
  }
  */
  const badgeUrl = `https://img.shields.io/badge/license-${data.badge}-informational`
  console.log(`renderLicenseLink:  ${badgeUrl}`);
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection() {
  if (data.badge) {
    renderLicenseBadge()
    console.log(`renderLicenseSection:  ${badgeConstruct}`)
    //const badgeComplete = `### License
    //                      ${badgeConstruct}\n\n`
    return `### License
    ${badgeConstruct}\n\n`
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  //renderLicenseSection();
  const badgeConstruct = renderLicenseBadge()
  return `
# ${data.projectname}\n
### Description\n
${data.description}\n\n
### License
${badgeConstruct}\n\n
### Index\n
- [Installation](#installation)
- [Usage Information](#usage)
- [Contribute](#contribute)
- [Testing](#testing)
- [Questions](#questions)\n
### Installation\n
${data.installation}\n\n
### Usage\n
${data.usage}\n\n
### Contribute\n
${data.contribute}\n\n
### Testing
${data.test}
### Questions?
For questions or comments feel free to reach out:\n
* **Email**:  [${data.email}](mailto:${data.email})
* **GitHub Profile**:  [${data.username}](https://github.com/${data.username})\n\n\n
----
<sub>Generated by Professional README Generator | 0.2.0 | 2021</sub>
`;
}

module.exports = generateMarkdown;
